// Generated by https://quicktype.io
// To parse this JSON data, do
//
//     final posts = postsFromJson(jsonString);

import 'dart:convert';

List<Posts> postsFromJson(String str) {
  final jsonData = json.decode(str);
  return new List<Posts>.from(jsonData.map((x) => Posts.fromJson(x)));
}

String postsToJson(List<Posts> data) {
  final dyn = new List<dynamic>.from(data.map((x) => x.toJson()));
  return json.encode(dyn);
}

class Posts {
  int userId;
  int id;
  String title;
  String body;

  Posts({
    this.userId,
    this.id,
    this.title,
    this.body,
  });

  factory Posts.fromJson(Map<String, dynamic> json) => new Posts(
    userId: json["userId"],
    id: json["id"],
    title: json["title"],
    body: json["body"],
  );

  Map<String, dynamic> toJson() => {
    "userId": userId,
    "id": id,
    "title": title,
    "body": body,
  };
}
